# Generated by Django 5.0.1 on 2026-01-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatistiqueGlobale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "total_workflows_actifs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workflows actifs"
                    ),
                ),
                (
                    "total_workflows_termines",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workflows terminés (jour)"
                    ),
                ),
                (
                    "total_evenements_ouverts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Événements ouverts"
                    ),
                ),
                (
                    "total_evenements_critiques",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Événements critiques"
                    ),
                ),
                (
                    "total_goulots_actifs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Goulots actifs"
                    ),
                ),
                (
                    "temps_attente_moyen_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps attente moyen (minutes)",
                    ),
                ),
                (
                    "temps_resolution_moyen_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps résolution moyen (minutes)",
                    ),
                ),
                (
                    "score_global_efficacite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score global d'efficacité",
                    ),
                ),
                (
                    "personnel_total_en_service",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Personnel total en service"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Statistique globale",
                "verbose_name_plural": "Statistiques globales",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AnalyseGoulotEtranglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DETECTE", "Détecté"),
                            ("EN_ANALYSE", "En analyse"),
                            ("CONFIRME", "Confirmé"),
                            ("RESOLU", "Résolu"),
                            ("FAUX_POSITIF", "Faux positif"),
                        ],
                        default="DETECTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MODEREE", "Modérée"),
                            ("ELEVEE", "Élevée"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MODEREE",
                        max_length=20,
                        verbose_name="Gravité",
                    ),
                ),
                (
                    "delai_moyen_minutes",
                    models.PositiveIntegerField(
                        help_text="Temps moyen de blocage observé",
                        verbose_name="Délai moyen (minutes)",
                    ),
                ),
                (
                    "nombre_occurrences",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre d'occurrences"
                    ),
                ),
                (
                    "impact_patients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Patients impactés"
                    ),
                ),
                (
                    "periode_debut",
                    models.DateTimeField(verbose_name="Début de période"),
                ),
                ("periode_fin", models.DateTimeField(verbose_name="Fin de période")),
                (
                    "recommandations",
                    models.TextField(
                        blank=True,
                        help_text="Actions recommandées pour résoudre le goulot",
                        verbose_name="Recommandations",
                    ),
                ),
                (
                    "detecte_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Détecté le"),
                ),
                (
                    "confirme_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmé le"
                    ),
                ),
                (
                    "resolu_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "confirme_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goulots_confirmes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmé par",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goulots",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "etape_concernee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goulots",
                        to="workflows.etapeworkflow",
                        verbose_name="Étape concernée",
                    ),
                ),
                (
                    "type_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goulots",
                        to="workflows.typeworkflow",
                        verbose_name="Type de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse de goulot d'étranglement",
                "verbose_name_plural": "Analyses de goulots d'étranglement",
                "ordering": ["-detecte_le"],
            },
        ),
        migrations.CreateModel(
            name="MetriqueDepartement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "workflows_demarre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workflows démarrés"
                    ),
                ),
                (
                    "workflows_termines",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workflows terminés"
                    ),
                ),
                (
                    "workflows_abandonnes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Workflows abandonnés"
                    ),
                ),
                (
                    "duree_moyenne_workflow_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durée moyenne workflow (minutes)",
                    ),
                ),
                (
                    "evenements_signales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Événements signalés"
                    ),
                ),
                (
                    "evenements_resolus",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Événements résolus"
                    ),
                ),
                (
                    "evenements_critiques",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Événements critiques"
                    ),
                ),
                (
                    "delai_resolution_moyen_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Délai résolution moyen (minutes)",
                    ),
                ),
                (
                    "personnel_en_service",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Personnel en service"
                    ),
                ),
                (
                    "score_efficacite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score de 0 à 100",
                        max_digits=5,
                        null=True,
                        verbose_name="Score d'efficacité",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metriques",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique de département",
                "verbose_name_plural": "Métriques de départements",
                "ordering": ["-date", "departement"],
                "unique_together": {("departement", "date")},
            },
        ),
    ]
