# Generated by Django 5.0.1 on 2026-01-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage_date', models.CharField(help_text='Ex: 2026-01-20 to 2026-01-27', max_length=100, verbose_name='Plage de dates')),
                ('donnees_metriques', models.JSONField(help_text='Statistiques agrégées', verbose_name='Données métriques')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Format')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-genere_le'],
            },
        ),
    ]
