# Generated by Django 5.0.1 on 2026-01-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("analytics", "0001_initial"),
        ("events", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegleAlerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_regle",
                    models.CharField(
                        choices=[
                            ("SEUIL_EVENEMENTS", "Seuil d'événements"),
                            ("SEUIL_TEMPS", "Seuil de temps"),
                            ("EVENEMENT_CRITIQUE", "Événement critique"),
                            ("GOULOT_DETECTE", "Goulot détecté"),
                            ("WORKFLOW_RETARD", "Workflow en retard"),
                        ],
                        max_length=30,
                        verbose_name="Type de règle",
                    ),
                ),
                (
                    "seuil_valeur",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Valeur numérique pour le déclenchement",
                        verbose_name="Valeur seuil",
                    ),
                ),
                (
                    "periode_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Période d'observation pour la règle",
                        verbose_name="Période (minutes)",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                            ("HAUTE", "Haute"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        max_length=20,
                        verbose_name="Priorité de l'alerte",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        default="{titre}: {description}",
                        help_text="Utilisez {titre}, {description}, {valeur}, {seuil}",
                        verbose_name="Modèle de message",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regles_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour tous les départements",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regles_alerte",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "type_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regles_alerte",
                        to="workflows.typeworkflow",
                        verbose_name="Type de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle d'alerte",
                "verbose_name_plural": "Règles d'alertes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                            ("HAUTE", "Haute"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "Nouvelle"),
                            ("VUE", "Vue"),
                            ("ACQUITTEE", "Acquittée"),
                            ("RESOLUE", "Résolue"),
                            ("IGNOREE", "Ignorée"),
                        ],
                        default="NOUVELLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "donnees_contexte",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Données de contexte"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "vue_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="Vue le"),
                ),
                (
                    "acquittee_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acquittée le"
                    ),
                ),
                (
                    "resolue_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolue le"
                    ),
                ),
                (
                    "acquittee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_acquittees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acquittée par",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="events.microevenement",
                        verbose_name="Événement lié",
                    ),
                ),
                (
                    "goulot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="analytics.analysegoulotetranglement",
                        verbose_name="Goulot lié",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="workflows.instanceworkflow",
                        verbose_name="Workflow lié",
                    ),
                ),
                (
                    "regle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes_generees",
                        to="alerts.reglealerte",
                        verbose_name="Règle source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-cree_le"],
                "indexes": [
                    models.Index(
                        fields=["-cree_le", "statut"],
                        name="alerts_aler_cree_le_9bd754_idx",
                    ),
                    models.Index(
                        fields=["priorite", "statut"],
                        name="alerts_aler_priorit_f2dcad_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AbonnementAlerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priorite_minimum",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                            ("HAUTE", "Haute"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMALE",
                        help_text="Recevoir les alertes de cette priorité et supérieures",
                        max_length=20,
                        verbose_name="Priorité minimum",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("APP", "Application"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                        ],
                        default="APP",
                        max_length=20,
                        verbose_name="Canal de notification",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "departements",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laisser vide pour tous les départements",
                        related_name="abonnes_alertes",
                        to="accounts.department",
                        verbose_name="Départements",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements_alertes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "types_regles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laisser vide pour toutes les règles",
                        related_name="abonnes",
                        to="alerts.reglealerte",
                        verbose_name="Types de règles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement aux alertes",
                "verbose_name_plural": "Abonnements aux alertes",
                "unique_together": {("utilisateur", "canal")},
            },
        ),
    ]
