# Generated by Django 5.0.1 on 2026-01-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "type_categorie",
                    models.CharField(
                        choices=[
                            ("RETARD", "Retard"),
                            ("BLOCAGE", "Blocage"),
                            ("EQUIPEMENT", "Problème d'équipement"),
                            ("COORDINATION", "Problème de coordination"),
                            ("RESSOURCE", "Manque de ressources"),
                            ("PATIENT", "Lié au patient"),
                            ("AUTRE", "Autre"),
                        ],
                        default="RETARD",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icone",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#FFA500",
                        help_text="Code couleur hexadécimal",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(default=0, verbose_name="Ordre"),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'événement",
                "verbose_name_plural": "Catégories d'événements",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="MicroEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "severite",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYEN", "Moyen"),
                            ("ELEVE", "Élevé"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="MOYEN",
                        max_length=20,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SIGNALE", "Signalé"),
                            ("EN_COURS", "En cours de traitement"),
                            ("RESOLU", "Résolu"),
                            ("IGNORE", "Ignoré"),
                        ],
                        default="SIGNALE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "delai_estime_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Impact estimé en minutes sur le workflow",
                        null=True,
                        verbose_name="Délai estimé (minutes)",
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True,
                        help_text="Emplacement précis de l'événement",
                        max_length=100,
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "survenu_le",
                    models.DateTimeField(
                        help_text="Date et heure de survenue de l'événement",
                        verbose_name="Survenu le",
                    ),
                ),
                (
                    "signale_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Signalé le"),
                ),
                (
                    "resolu_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "commentaire_resolution",
                    models.TextField(
                        blank=True, verbose_name="Commentaire de résolution"
                    ),
                ),
                (
                    "est_recurrent",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si ce type d'événement se répète fréquemment",
                        verbose_name="Récurrent",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="events.categorieevenement",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "instance_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="workflows.instanceworkflow",
                        verbose_name="Instance de workflow",
                    ),
                ),
                (
                    "rapporteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_rapportes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rapporteur",
                    ),
                ),
                (
                    "resolu_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_resolus",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Résolu par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Micro-événement",
                "verbose_name_plural": "Micro-événements",
                "ordering": ["-signale_le"],
            },
        ),
        migrations.CreateModel(
            name="CommentaireEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentaires_evenements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="events.microevenement",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PieceJointeEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="evenements/pieces_jointes/", verbose_name="Fichier"
                    ),
                ),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("DOCUMENT", "Document"),
                            ("AUDIO", "Audio"),
                        ],
                        default="IMAGE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "nom_original",
                    models.CharField(max_length=255, verbose_name="Nom original"),
                ),
                (
                    "ajoute_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="events.microevenement",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
            },
        ),
        migrations.AddIndex(
            model_name="microevenement",
            index=models.Index(
                fields=["-signale_le"], name="events_micr_signale_834da6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="microevenement",
            index=models.Index(
                fields=["departement", "statut"], name="events_micr_departe_c1f561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="microevenement",
            index=models.Index(
                fields=["severite", "statut"], name="events_micr_severit_991fbb_idx"
            ),
        ),
    ]
