# Generated by Django 5.0.1 on 2026-01-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHospitalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('NORMAL', 'Normal'), ('TENSION', 'Tension')], default='NORMAL', max_length=20, verbose_name='État')),
                ('saturation', models.PositiveIntegerField(default=0, help_text='Pourcentage de saturation du service', verbose_name='Saturation (%)')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to='accounts.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Service Hospitalier',
                'verbose_name_plural': 'Services Hospitaliers',
                'ordering': ['department__name'],
            },
        ),
    ]
