export const Colors = {
    light: {
        primary: '#1E88E5',
        accent: '#7E57C2',
        background: '#F4F6F8',
        surface: '#FFFFFF',
        text: '#1C1C1E',
        textSecondary: '#6C757D',
        border: '#E0E0E0',
        error: '#E53935',
        success: '#43A047',
        warning: '#FB8C00',
        tint: '#1E88E5',
        tabIconDefault: '#6C757D',
        tabIconSelected: '#1E88E5',
    },
    dark: {
        primary: '#1E88E5',
        accent: '#7E57C2',
        background: '#1A1C1E',
        surface: '#2C2C2E',
        text: '#FFFFFF',
        textSecondary: '#A1A1AA',
        border: '#404040',
        error: '#E53935',
        success: '#43A047',
        warning: '#FB8C00',
        tint: '#fff',
        tabIconDefault: '#ccc',
        tabIconSelected: '#fff',
    },
};
