# Generated by Django 5.0.1 on 2026-01-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("ADMISSION", "Admission patient"),
                            ("LABORATOIRE", "Examens de laboratoire"),
                            ("URGENCE", "Service des urgences"),
                            ("CHIRURGIE", "Bloc opératoire"),
                            ("RADIOLOGIE", "Imagerie médicale"),
                            ("CONSULTATION", "Consultation externe"),
                            ("HOSPITALISATION", "Hospitalisation"),
                            ("SORTIE", "Sortie patient"),
                        ],
                        default="ADMISSION",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duree_standard_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Durée attendue pour compléter ce type de workflow",
                        verbose_name="Durée standard (minutes)",
                    ),
                ),
                (
                    "seuil_alerte_minutes",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Durée au-delà de laquelle une alerte est déclenchée",
                        verbose_name="Seuil d'alerte (minutes)",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Type de workflow",
                "verbose_name_plural": "Types de workflows",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="EtapeWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de l'étape"),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "duree_estimee_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                (
                    "est_obligatoire",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "departement_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapes_responsables",
                        to="accounts.department",
                        verbose_name="Département responsable",
                    ),
                ),
                (
                    "type_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapes",
                        to="workflows.typeworkflow",
                        verbose_name="Type de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de workflow",
                "verbose_name_plural": "Étapes de workflows",
                "ordering": ["type_workflow", "ordre"],
                "unique_together": {("type_workflow", "code")},
            },
        ),
        migrations.CreateModel(
            name="InstanceWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_patient",
                    models.CharField(
                        help_text="Identifiant anonymisé du patient",
                        max_length=50,
                        verbose_name="Référence patient",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("INITIE", "Initié"),
                            ("EN_COURS", "En cours"),
                            ("EN_PAUSE", "En pause"),
                            ("TERMINE", "Terminé"),
                            ("ABANDONNE", "Abandonné"),
                        ],
                        default="INITIE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                            ("HAUTE", "Haute"),
                            ("URGENTE", "Urgente"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="NORMALE",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "demarre_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Démarré le"),
                ),
                (
                    "termine_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances_workflow",
                        to="accounts.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "etape_actuelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances_actuelles",
                        to="workflows.etapeworkflow",
                        verbose_name="Étape actuelle",
                    ),
                ),
                (
                    "initie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_inities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initié par",
                    ),
                ),
                (
                    "type_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflows.typeworkflow",
                        verbose_name="Type de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance de workflow",
                "verbose_name_plural": "Instances de workflows",
                "ordering": ["-demarre_le"],
            },
        ),
        migrations.CreateModel(
            name="TransitionEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "duree_etape_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée de l'étape (minutes)"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "effectuee_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectuée par",
                    ),
                ),
                (
                    "etape_destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_entrantes",
                        to="workflows.etapeworkflow",
                        verbose_name="Étape destination",
                    ),
                ),
                (
                    "etape_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions_sortantes",
                        to="workflows.etapeworkflow",
                        verbose_name="Étape source",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflows.instanceworkflow",
                        verbose_name="Instance de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition d'étape",
                "verbose_name_plural": "Transitions d'étapes",
                "ordering": ["instance", "horodatage"],
            },
        ),
    ]
