from django.db import models
from django.contrib.auth.models import User

class Service(models.Model):
    """
    Represents a hospital department/unit.
    Can be in 'Normal' or 'Tension' state (State Pattern).
    """
    STATE_CHOICES = [
        ('NORMAL', 'Normal'),
        ('TENSION', 'Tension'),
    ]
    nom = models.CharField(max_length=100)
    localisation = models.CharField(max_length=200)
    etat = models.CharField(max_length=20, choices=STATE_CHOICES, default='NORMAL')

    def __str__(self):
        return f"{self.nom} ({self.etat})"

class TypeFlux(models.Model):
    """
    Predefined types of workflows (e.g., Lab Result, Patient Transfer).
    """
    nom = models.CharField(max_length=100)
    duree_standard = models.IntegerField(help_text="Standard duration in seconds")

    def __str__(self):
        return self.nom

class MicroEvenement(models.Model):
    """
    A specific event signal logged by healthcare staff.
    """
    GRAVITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('CRITICAL', 'Critical'),
    ]
    personnel = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events_reported')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='events')
    type_flux = models.ForeignKey(TypeFlux, on_delete=models.CASCADE, related_name='events')
    horodatage = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, null=True)
    niveau_gravite = models.CharField(max_length=20, choices=GRAVITY_CHOICES, default='LOW')
    est_valide = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.type_flux.nom} at {self.horodatage} ({self.niveau_gravite})"

class Alerte(models.Model):
    """
    System generated alert when thresholds are exceeded.
    """
    GRAVITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('CRITICAL', 'Critical'),
    ]
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='alerts')
    message = models.TextField()
    niveau_gravite = models.CharField(max_length=20, choices=GRAVITY_CHOICES, default='HIGH')
    genere_le = models.DateTimeField(auto_now_add=True)
    est_resolu = models.BooleanField(default=False)

    def __str__(self):
        return f"Alert for {self.service.nom} ({self.niveau_gravite}) - {self.genere_le}"

class Rapport(models.Model):
    """
    Statistical reports generated by the system.
    """
    plage_date = models.CharField(max_length=100) # e.g., "2026-01-20 to 2026-01-27"
    donnees_metriques = models.JSONField() # Stores aggregated stats
    genere_le = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report {self.plage_date}"
